# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tech memorandums
email: alephnull@hcoop.net
description: > # this means to ignore newlines until "baseurl:"
  An aide-mémoire for the things I do and then forget how I did them.
  Future me thanks you.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alephnull.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  alephnull

# Build settings
markdown: kramdown
